### ISSUE TITLE
extra slurm headers do not overwrite existing slurm headers

### ISSUE THREAD

**Issue by d3sm0** [ministry-of-silly-code/experiment_buddy#120]
Suppose we have in the `srun_python.sh` an header such:
```
#SBATCH --time=2-00:00
```
and we add:
```
#SBATCH --time=12:00:00
```
The resulting script contains both parameters, but first come first served, and the first parameter will always have a preference.

**Comment by manuel-delverme** [comment]
They do, is this not happening?
